// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `DemoMaps.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


// Freeze types in this file:
// name="ByteMap", key="int", value="demo::ByteSeq"
// name="StringMap", key="int", value="demo::StringSeq"
// name="StringDoubleMap", key="int", value="demo::StringDouble"
// name="FixedMap", key="int", value="demo::Fixed"

#ifndef __c__Users_Alberto_Desktop_DemoMaps_h__
#define __c__Users_Alberto_Desktop_DemoMaps_h__

#include <Freeze/Map.h>
#include "demo.h"

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

class ByteMapKeyCodec
{
public:

    static void write(::Ice::Int, Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Ice::Int&, const Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

class ByteMapValueCodec
{
public:

    static void write(const ::Demo::ByteSeq&, Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Demo::ByteSeq&, const Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

typedef Freeze::Map< ::Ice::Int, ::Demo::ByteSeq, ByteMapKeyCodec, ByteMapValueCodec, Freeze::IceEncodingCompare > ByteMap;

class StringMapKeyCodec
{
public:

    static void write(::Ice::Int, Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Ice::Int&, const Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

class StringMapValueCodec
{
public:

    static void write(const ::Demo::StringSeq&, Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Demo::StringSeq&, const Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

typedef Freeze::Map< ::Ice::Int, ::Demo::StringSeq, StringMapKeyCodec, StringMapValueCodec, Freeze::IceEncodingCompare > StringMap;

class StringDoubleMapKeyCodec
{
public:

    static void write(::Ice::Int, Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Ice::Int&, const Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

class StringDoubleMapValueCodec
{
public:

    static void write(const ::Demo::StringDouble&, Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Demo::StringDouble&, const Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

typedef Freeze::Map< ::Ice::Int, ::Demo::StringDouble, StringDoubleMapKeyCodec, StringDoubleMapValueCodec, Freeze::IceEncodingCompare > StringDoubleMap;

class FixedMapKeyCodec
{
public:

    static void write(::Ice::Int, Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Ice::Int&, const Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

class FixedMapValueCodec
{
public:

    static void write(const ::Demo::Fixed&, Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Demo::Fixed&, const Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

typedef Freeze::Map< ::Ice::Int, ::Demo::Fixed, FixedMapKeyCodec, FixedMapValueCodec, Freeze::IceEncodingCompare > FixedMap;

#endif
